version: "3.6"

volumes:
  samba-data:
    driver: local
  another-samba-data:
    driver: local

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "6622:22"
    command: "foo:pass:1001:1001:upload"
    volumes:
      - ${PWD}/src/test/resources/ssh/id_rsa.pub:/home/foo/.ssh/authorized_keys

  # https://github.com/fauria/docker-vsftpd/issues/41
  ftp:
    image: markhobson/vsftpd
    ports:
      - "6621:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: guest
      FTP_PASS: guest
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110

  ftps:
    image: pcavezzan/ftpsdev
    ports:
      - "6990:21"
      - "50000-50009:50000-50009"
    environment:
      FTP_USER: guest
      FTP_PWD: guest

  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: ssh
    hostname: ssh
    environment:
      PUID: 48
      PGID: 48
      TZ: Etc/UTC
      LOG_STDOUT: true
      PASSWORD_ACCESS: true
      USER_PASSWORD: password
      USER_NAME: foo
      PUBLIC_KEY_DIR: /app/ssh
    ports:
      - 2222:2222
    restart: unless-stopped
    volumes:
      - ${PWD}/src/test/resources/ssh/id_ed25519.pub:/app/ssh/id_ed25519.pub

  samba:
    image: elswork/samba
    container_name: samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - samba-data:/share/data/to_share
      - another-samba-data:/share/data/second_share
    entrypoint: /bin/bash -c
    command: >
      'sed -i "\$$i chown -R 1000:1000 /share/data" /entrypoint.sh &&
      /entrypoint.sh
      -u "1000:1000:alice:alice:alipass"
      -s "upload:/share/data/to_share:rw:alice"
      -s "another_upload:/share/data/second_share:rw:alice"'
