version: "3.6"

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "6622:22"
    command: "foo:pass:1001:1001:upload"
    volumes:
      - ${PWD}/id_rsa.pub:/home/foo/.ssh/authorized_keys

  # https://github.com/fauria/docker-vsftpd/issues/41
  ftp:
    image: markhobson/vsftpd
    ports:
      - "6621:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: guest
      FTP_PASS: guest
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110

  ftps:
    image: pcavezzan/ftpsdev
    ports:
      - "6990:21"
      - "50000-50009:50000-50009"
    environment:
      FTP_USER: guest
      FTP_PWD: guest

  ssh:
    image: panubo/sshd
    ports:
      - "2222:22"
    environment:
      SSH_USERS: foo:48:48
      SSH_ENABLE_PASSWORD_AUTH: "true"
    volumes:
      - ${PWD}/src/test/resources/ssh/:/etc/entrypoint.d/
