version: "3.6"



services:
  sftp:
      build: docker/sftp
      ports:
          - "6622:22"
      command: foo:pass:1001
      volumes:
        - ${HOME}/.ssh/id_rsa.pub:/home/foo/.ssh/authorized_keys   
#  sftp-deb:
#      build: docker/sftp-deb
#      ports:
#          - "6722:22"
