group: io.kestra.plugin.fs.local
name: "local"
title: "Local"
description: "Tasks that manipulate files on the local file system."
body: "Use local path inputs to upload, download, list, copy, move, or delete files and enable the polling trigger to react to new or modified files in directories."
videos: []
createdBy: "Kestra Core Team"
managedBy: "Kestra Core Team"
